# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27a3c2a299b0750ff27b08bece6a44a398730fcbdd27d13eddde3194ce0c78ff12731edad63ecda598069b6acc4627f6fafd5bccffcca08f7505713243b1f0af

test:
  secret_key_base: 17a830e3c6ef4adb2a73e11f86d1dfbc71e4d859f406645d584ac92a34181bd1e5de01c9310bd2c606e76419f2dba3860c39a133276567fcf4ddc5367e63b263

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
